name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build image:
    name: build image
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/falentio/meowvie:latest

